# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-ci-pipeline

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '75f14b00-96a5-4d30-b29a-38817d667b10'
    pipeline: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'specific'
    buildId: '44'
    downloadType: 'single'
    artifactName: 'app'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: HelmDeploy@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '953dfd1d-b9e0-46c2-a58d-c644f04794e3'
    azureResourceGroup: 'Kubernetes-Course'
    kubernetesCluster: 'robot-dreams-cluster'
    namespace: 'northwindstore-helm'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(System.ArtifactsDirectory)/app/Chart.yaml'
    releaseName: 'northwindstore'
    overrideValues: 'ingress.hosts[0].host=helm.northwindstore.local, ingress.hosts[0].paths[0].path=/, ingress.hosts[0].paths[0].pathType=Prefix, ingress.tls[0].hosts[0]=helm.northwindstore.local, ingress.tls[0].secretName=ingress-tls'
    valueFile: 'ci/app/values.yaml'
    arguments: --install
