# Starter pipeline
trigger:
 - none

pool:
  vmImage: ubuntu-latest

# Define the pipeline resource with an alias
resources:
  pipelines:
  - pipeline: build-pipeline  # This is the alias
    source: 'VojtaKai.kubernetes-build'  # The name of the build pipeline
    project: '75f14b00-96a5-4d30-b29a-38817d667b10'
    branch: 'release-cd-pipeline'  # or the branch your build pipeline uses

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '75f14b00-96a5-4d30-b29a-38817d667b10'
    pipeline: '1'
    buildVersionToDownload: 'latest'
    artifactName: 'app'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: HelmDeploy@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '953dfd1d-b9e0-46c2-a58d-c644f04794e3'
    azureResourceGroup: 'Kubernetes-Course'
    kubernetesCluster: 'robot-dreams-cluster'
    namespace: 'northwindstore-helm'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '$(System.ArtifactsDirectory)/app'
    releaseName: 'northwindstore'
    overrideValues: |
      ingress.hosts[0].host=helm.northwindstore.local
      ingress.hosts[0].paths[0].path=/
      ingress.hosts[0].paths[0].pathType=Prefix
      ingress.tls[0].hosts[0]=helm.northwindstore.local
      ingress.tls[0].secretName=ingress-tls
      image.tag=$(Resources.Pipeline.build-pipeline.RunID)
    valueFile: '$(System.ArtifactsDirectory)/app/values.yaml'